<a href="https://colab.research.google.com/github/bariskucuk1999/data-science-notes/blob/main/Veri_%C3%96n_%C4%B0%C5%9Fleme(Data_Preprocessing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
veriler=pd.read_csv("veriler.txt")
boyKilo=veriler[["boy","kilo"]]
boyKilo

**Eksik Verileri Tamamlamak**

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")
Yas=veriler.iloc[:,1:4].values
imputer=imputer.fit(Yas[:,1:4])
Yas[:,1:4]=imputer.transform(Yas[:,1:4])
Yas

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]])

**Kategorik Verilerin Encode Edilmesi (Sayısal Değere Dönüştürülmesi)**

In [ ]:
#nominal ve ordinal(kategorik veriler)-->numeric
ulke=veriler.iloc[:,0:1].values
from sklearn import preprocessing
le=preprocessing.LabelEncoder() #kategorik column dönüşümü için
ulke[:,0]=le.fit_transform(veriler.iloc[:,0])
ohe=preprocessing.OneHotEncoder() #column başlıklarını etiketlere taşıma ve her etiketin altında 0 veya 1 aitliğini belirleme
ulke=ohe.fit_transform(ulke).toarray() #tek aşamada fit&transform (önişlemedeki öğrenme ve dönüştürme süreci)
sonuc=pd.DataFrame(data=ulke, index=range(22),columns=["fr","tr","us"]) #numpy dizisi-->dataframe
sonuc2=pd.DataFrame(data=Yas, index=range(22),columns=["boy","kilo","yas"])
cinsiyet=veriler.iloc[:,-1].values
sonuc3=pd.DataFrame(data=cinsiyet,index=range(22),columns=["cinsiyet"])
s=pd.concat([sonuc,sonuc2],axis=1) #dataframe'lerin birleştirilmesi
s2=pd.concat([s,sonuc3],axis=1)
s2

     fr   tr   us  boy  kilo  yas cinsiyet
0   0.0  1.0  0.0  130    30   10        e
1   0.0  1.0  0.0  125    36   11        e
2   0.0  1.0  0.0  135    34   10        k
3   0.0  1.0  0.0  133    30    9        k
4   0.0  1.0  0.0  129    38   12        e
5   0.0  1.0  0.0  180    90   30        e
6   0.0  1.0  0.0  190    80   25        e
7   0.0  1.0  0.0  175    90   35        e
8   0.0  1.0  0.0  177    60   22        k
9   0.0  0.0  1.0  185   105   33        e
10  0.0  0.0  1.0  165    55   27        k
11  0.0  0.0  1.0  155    50   44        k
12  0.0  0.0  1.0  160    58   39        k
13  0.0  0.0  1.0  162    59   41        k
14  0.0  0.0  1.0  167    62   55        k
15  1.0  0.0  0.0  174    70   47        e
16  1.0  0.0  0.0  193    90   23        e
17  1.0  0.0  0.0  187    80   27        e
18  1.0  0.0  0.0  183    88   28        e
19  1.0  0.0  0.0  159    40   29        k
20  1.0  0.0  0.0  164    66   32        k
21  1.0  0.0  0.0  166    56   42        k

**Verilerin Eğitim ve Test İçin Bölünmesi**

In [ ]:
#ulke, boy ve yas'tan cinsiyeti tahmin etme
from sklearn.model_selection import train_test_split #verinin satır bazlı bölünmesi
x_train, x_test, y_train, y_test=train_test_split(s,sonuc3,test_size=0.33,random_state=0)#verinin bağımlı ve bağımsız değişken olarak bölünmesi
x_train
y_train
#dikey eksende bağımlı ve bağımsız değişkenler olarak, yatay eksende train ve test(eğitim ve test) kümesi olarak ikiye ayırıyoruz)

   cinsiyet
8         k
6         e
16        e
4         e
2         k
5         e
17        e
9         e
7         e
18        e
3         k
0         e
15        e
12        k

**Sayısal Değerlerin Ölçeklenmesi**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)
#farklı anlamlardaki verilerin ortak anlama çekilmesi
#bir kişinin cinsiyetini tahmin etmede boy, yaş, kilonun etkisi nedir için ortalamasını alırsak belli bir değer olarak gelmesi(50-100 arası gibi)